services:
  db:
    image: postgres:15
    env_file: .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    env_file: .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    ports:
      - "${MINIO_HOST_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data

  web:
    build: .
    env_file: .env
    depends_on:
      - db
      - minio
    volumes:
      - .:/app                   # your code
      - staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    command:
      - gunicorn
      - djangoProject3.wsgi:application
      - --bind
      - 0.0.0.0:8000
      - --workers
      - "2"

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - staticfiles:/usr/share/nginx/html/static:ro
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_data:
  minio_data:
  staticfiles:
