version: '3.8'

services:
  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    env_file:
      - .env
    ports:
      - "${MINIO_HOST_PORT}:9000"     # S3 API порт
      - "${MINIO_CONSOLE_PORT}:9001"  # Web-консоль
    volumes:
      - minio_data:/data

  web:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - minio
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=djangoProject3.settings

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - staticfiles:/usr/share/nginx/html/static:ro
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_data:
  minio_data:
  staticfiles:
